project:
  type: website
preview:
  exclude:
    - "Take_Home_Exercises/Take_Home_Exercise_1/Take_Home_Exercise1.qmd"
website:
  title: "Street Surfers"
  navbar:
    left:
      - text: "Project Description"
        href: "ProjectDescription/ProjectDescription.html"
      - text: "Poster"
        href: "Poster/Poster.html"
      - text: "Application User Guide"
        href: "UserGuide/UserGuide.html"
      - text: "Web Shiny App"
        href: "WebShinyApp/WebShiny.html"

    right:
      - href: index.qmd
        text: "Home"
        icon: fas fa-home
      - href: About/about.qmd
        text: "About Us"
   
format:
  html:
    theme: Zephyr 
    freeze: false
    css: styles.css # Custom styles for non-code elements
    toc: true
    toc-location: right

editor: visual
